spring:
  application:
    name: sc-eureka
  profiles:
    # 选择激活哪个profiles
    active: sc-eureka

---
spring:
  profiles: sc-eureka
server:
  port: 8761
eureka:
  client:
    # 禁止注册中心自己注册进来
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://sc-eureka:8761/eureka/
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      # 填入其他两个eureka服务的地址和端口，多个服务用逗号隔开
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer3:8763/eureka/,http://peer1:8761/eureka/
---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
