version: "3.2" #版本号
services:
  # 注册中心
  sc-eureka: #服务名称（不是容器名）
    image: mcpayment/ubuntu1404-java8:latest  #使用的镜像
    # 添加主机名的标签，
    # 相当于在docker中的/etc/hosts文件中添加一些记录
    extra_hosts:
     - "sc-eureka:127.0.0.1"
    ports:
      - "8761:8761"  #暴露的端口信息和docker run -d -p 80:80 一样
    expose:
      - "8761"
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: sc-eureka #容器名称
    #挂载文件ps:如果是挂载文件必须在容器中也指定名称，推荐是挂载文件夹，下面只是做个文件挂载的案例也可以
    #挂载文件夹/root/compose_test/jdk/:/data
    volumes:
      - ./sc-eureka/target/sc-eureka-0.0.1-SNAPSHOT-exe.jar:/sc-eureka-0.0.1-SNAPSHOT-exe.jar
    entrypoint: java -Xms128m -Xmx256m -jar /sc-eureka-0.0.1-SNAPSHOT-exe.jar #启动容器后执行的命令

  # 配置中心
  sc-config:
    image: mcpayment/ubuntu1404-java8:latest
    ports:
      - "8888:8888"
    expose:
      - "8888"
    restart: "always"
    container_name: sc-config
    volumes:
      - ./sc-config/target/sc-config-0.0.1-SNAPSHOT-exe.jar:/sc-config-0.0.1-SNAPSHOT-exe.jar
      - ./repo-config/:/repo-config
    entrypoint: java -Xms64m -Xmx128m -jar /sc-config-0.0.1-SNAPSHOT-exe.jar
    extra_hosts:
     - "sc-eureka:192.168.0.220"
    depends_on:
      - sc-eureka

  # 网关
  sc-gateway:
    image: mcpayment/ubuntu1404-java8:latest
    ports:
      - "9000:9000"
    expose:
      - "9000"
#    restart: "always"
    container_name: sc-gateway
    volumes:
      - ./sc-gateway/target/sc-gateway-0.0.1-SNAPSHOT-exe.jar:/sc-gateway-0.0.1-SNAPSHOT-exe.jar
    entrypoint: java -Xms64m -Xmx128m -jar /sc-gateway-0.0.1-SNAPSHOT-exe.jar
    extra_hosts:
      - "sc-eureka:192.168.0.220"
      - "rabbitmq:192.168.0.220"
    depends_on:
      - sc-eureka
      - sc-config

  # 测试服务
  svc-test:
    image: mcpayment/ubuntu1404-java8:latest
    ports:
      - "9999:9999"
    expose:
      - "9999"
#    restart: "always"
    container_name: svc-test
    volumes:
      - ./svc-test/target/svc-test-0.0.1-SNAPSHOT-exe.jar:/svc-test-0.0.1-SNAPSHOT-exe.jar
    entrypoint: java -Xms64m -Xmx128m -jar /svc-test-0.0.1-SNAPSHOT-exe.jar
    extra_hosts:
      - "sc-eureka:192.168.0.220"
      - "rabbitmq:192.168.0.220"
    depends_on:
      - sc-eureka
      - sc-config