package com.vicchan.svc.demo.log.mapper;

import com.vicchan.svc.demo.log.pojo.LogDO;
import com.vicchan.svc.demo.log.pojo.LogDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogDOMapper {
    long countByExample(LogDOExample example);

    int deleteByExample(LogDOExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LogDO record);

    int insertSelective(LogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LogDO selectOneByExample(LogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LogDO selectOneByExampleSelective(@Param("example") LogDOExample example, @Param("selective") LogDO.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LogDO> selectByExampleSelective(@Param("example") LogDOExample example, @Param("selective") LogDO.Column ... selective);

    List<LogDO> selectByExample(LogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LogDO selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LogDO.Column ... selective);

    LogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LogDO selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    int updateByExampleSelective(@Param("record") LogDO record, @Param("example") LogDOExample example);

    int updateByExample(@Param("record") LogDO record, @Param("example") LogDOExample example);

    int updateByPrimaryKeySelective(LogDO record);

    int updateByPrimaryKey(LogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scs_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}