#
# application：所有微服务的通用配置
# application-dev：所有微服务的dev(开发环境)配置
# application-prod：所有微服务的prod(生产环境)配置
#
eureka:
  client:
    serviceUrl:
      # 注册到任何一个eureka服务都可以（peer1，peer2，peer3）
      defaultZone: http://sc-eureka:8761/eureka/

spring:
  cloud:
    bus:
      trace:
        # 追踪开关?
        enabled: true
      # 开启消息总线的功能
      enabled: true

  # rabbitmq相关配置
  # 要在/etc/hosts文件中配置rabbitmq的映射
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      # 指定暴露的接口
      exposure:
        # 消息总线刷新的接口名称
#        include: bus-refresh
        # 暴露所有接口
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"







