server:
  port: 9000

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 默认为true，表示会同时创建一个与对应服务同名的访问路径，如localhost:9000/svc-test/hi
          enabled: false
          lowerCaseServiceId: true
      routes:
      # 路径id，唯一标识一个路径
      - id: svc-test
        # lb://SVC-TEST即svc-test服务的负载均衡地址
        uri: lb://SVC-TEST
        predicates:
          # 将以/test/**开头的请求转发到上面的uri
          - Path=/test/**
        filters:
          # StripPrefix=1表示在转发之前去掉路径中的第一个目录，即去掉/demo
          - StripPrefix=1
          # - RequestTime=true
  zipkin:
    # 默认url
#    base-url: http://localhost:9411
    sender:
      # 支持三种 方式  RABBIT, KAFKA, WEB
      # 把链路信息先推入kafka，zipkin再从kafka中获取
      # 需要配合在zipkin启动时，添加以下参数- DKAFKA_BOOTSTRAP_SERVERS=192.168.0.220:9092
      type: kafka
    service:
      name: ${spring.application.name} #可以和 application.name 同名 但是kafka模式下必须设置
  sleuth:
    sampler:
      # 默认采集率为0.1，1为全部采集
      probability: 1
  kafka:
#    bootstrap-servers: ${server.ip}:9092
    bootstrap-servers: 192.168.0.220:9092
eureka:
  # 注意，在非必要时不要写hostname，可能会导致网关失效
  # instance:
  #   hostname: localhost
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug



