# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-elasticsearch container instead of the zipkin-mysql container.

version: '2'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    environment:
      # 从kafka中获取信息。注意，在logstash中不要抓取zipkin主题的kafka信息，否则会导致zipkin无法正常获取kafka信息
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # 把链路信息保存到ES中
      - STORAGE_TYPE=elasticsearch
      # ES主机地址
      - ES_HOSTS=http://elasticsearch:9200
      # ES登录用户名
      - ES_USERNAME=elastic
      # ES登录密码
      - ES_PASSWORD=changeme
      #- JAVA_OPTS=-Xmx256M -Xms256M
      - JAVA_OPTS=-Xmx256M -Xms256M -Dlogging.level.zipkin=INFO -Dlogging.level.zipkin2=INFO
    restart: "always"
    #mem_limit: 600000000 # 内存限制
  zipkin2:
    container_name: zipkin2
    image: openzipkin/zipkin:latest
    environment:
      # 从kafka中获取信息。注意，在logstash中不要抓取zipkin主题的kafka信息，否则会导致zipkin无法正常获取kafka信息
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # 把链路信息保存到ES中
      - STORAGE_TYPE=elasticsearch
      # ES主机地址
      - ES_HOSTS=http://elasticsearch:9200
      # ES登录用户名
      - ES_USERNAME=elastic
      # ES登录密码
      - ES_PASSWORD=changeme
      #- JAVA_OPTS=-Xmx256M -Xms256M
      - JAVA_OPTS=-Xmx256M -Xms256M -Dlogging.level.zipkin=INFO -Dlogging.level.zipkin2=INFO
    restart: "always"
    #mem_limit: 600000000 # 内存限制
  zipkin3:
    container_name: zipkin3
    image: openzipkin/zipkin:latest
    environment:
      # 从kafka中获取信息。注意，在logstash中不要抓取zipkin主题的kafka信息，否则会导致zipkin无法正常获取kafka信息
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # 把链路信息保存到ES中
      - STORAGE_TYPE=elasticsearch
      # ES主机地址
      - ES_HOSTS=http://elasticsearch:9200
      # ES登录用户名
      - ES_USERNAME=elastic
      # ES登录密码
      - ES_PASSWORD=changeme
      #- JAVA_OPTS=-Xmx256M -Xms256M
      - JAVA_OPTS=-Xmx256M -Xms256M -Dlogging.level.zipkin=INFO -Dlogging.level.zipkin2=INFO
    restart: "always"
    #mem_limit: 600000000 # 内存限制
  zipkin-haproxy:
    container_name: zipkin-haproxy
    build:
      dockerfile: Dockerfile
      context: ./
    restart: "always"
    depends_on:
      - zipkin
      - zipkin2
      - zipkin3
    ports:
      - 9411:9411
      - 1936:1936
