# This file uses the version 2 docker-compose file format, described here:
# https://docs.docker.com/compose/compose-file/#version-2
#
# It extends the default configuration from docker-compose.yml to run the
# zipkin-elasticsearch container instead of the zipkin-mysql container.

version: '2'

services:
  zipkin-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-one
    environment:
      # 从kafka中获取信息。注意，在logstash中不要抓取zipkin主题的kafka信息，否则会导致zipkin无法正常获取kafka信息
      - DKAFKA_BOOTSTRAP_SERVERS=192.168.0.220:9092
      # 把链路信息保存到ES中
      - STORAGE_TYPE=elasticsearch
      # ES主机地址
      - ES_HOSTS=http://192.168.0.220:9200
      # ES登录用户名
      - ES_USERNAME=elastic
      # ES登录密码
      - ES_PASSWORD=changeme
      - JAVA_OPTS=-Dlogging.level.zipkin=INFO -Dlogging.level.zipkin2=INFO
    networks:
      - zipkin
# 本地运行先去掉集群配置，省内存（集群环境已验证成功）
#  zipkin-two:
#    image: openzipkin/zipkin:latest
#    container_name: zipkin-two
#    environment:
#      - DKAFKA_BOOTSTRAP_SERVERS=192.168.0.220:9092
#      - STORAGE_TYPE=elasticsearch
#      - ES_HOSTS=http://192.168.0.220:9200
##      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
#    networks:
#      - zipkin
#  zipkin-three:
#    image: openzipkin/zipkin:latest
#    container_name: zipkin-three
#    environment:
#      - DKAFKA_BOOTSTRAP_SERVERS=192.168.0.220:9092
#      - STORAGE_TYPE=elasticsearch
#      - ES_HOSTS=http://192.168.0.220:9200
##      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
#    networks:
#      - zipkin
  haproxy:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - zipkin-one
      # 本地运行先去掉集群配置，省内存（集群环境已验证成功）
#      - zipkin-two
#      - zipkin-three
    ports:
      - 9411:9411
      - 1936:1936
    networks:
      - zipkin

networks:
  zipkin:
    driver: bridge
