eureka:
  instance:
    hostname: sc-eureka
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: sc-config
  profiles:
    # native：使用本地仓库
    # git：使用远程仓库
    active: native,sc-config
  cloud:
    config:
      label: master
      server:
        # 使用本地属性文件
        # 属性文件地址，只要指定文件夹的路径
        native:
          search-locations: ./repo-config
        # 使用远程仓库
        git:
          # gitlab一定要以.git结束，github不用
          # 注：需要服务器有访问该git仓库的密钥
          uri: https://github.com/VicChanS/spring-cloud-sample
          search-paths: repo-config
          username:
          password:
          # 强制拉属性，如果本地副本是脏的，它将使Spring Cloud配置服务器从远程存储库中强制pull.
          force-pull: true

---
spring:
  profiles: sc-config

server:
  port: 8888

---
spring:
  profiles: sc-config2

server:
  port: 8889