server:
  port: 8888

spring:
  application:
    name: sc-config
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/

---
spring:
  # 表示使用本地方式读取配置文件
  profiles:
    active: git
  cloud:
    config:
      server:
        # 使用本地属性文件
        # 属性文件地址，只要指定文件夹的路径
        native:
          search-locations: /Users/vicchan/CodeMonkey/MyProjects/spring-cloud-sample/repo-config

---
spring:
  # 表示使用git方式读取配置文件
  profiles:
    active: git
  cloud:
    config:
      label: master
      server:
        # 使用远程仓库
        git:
          # gitlab一定要以.git结束，github不用
          # 注：需要服务器有访问该git仓库的密钥
          uri: https://github.com/VicChanS/spring-cloud-sample
          search-paths: repo-config
          username:
          password: