server:
  port: 9998

spring:
  application:
    name: svc-test
  zipkin:
    # 默认url
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 默认采集率为0.1，1为全部采集
      probability: 1

eureka:
  client:
    serviceUrl:
      # 注册到任何一个eureka服务都可以（peer1，peer2，peer3）
      defaultZone: http://peer1:8761/eureka/

